namespace: servicenow
name: servicenow
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies: {}
repository: git@github.com:coll-test/servicenow.servicenow.git
documentation: https://github.com/coll-test/servicenow.servicenow/tree/master/docs
homepage: https://github.com/coll-test/servicenow.servicenow
issues: https://github.com/coll-test/servicenow.servicenow/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
